# Server
server.port = 4000

# Spring
spring.mvc.throw-exception-if-no-handler-found = true
spring.resources.add-mappings = false

# Datasource
spring.datasource.url = jdbc:mysql://localhost:3306/beagle?serverTimezone=UTC&allowLoadLocalInfile=true
spring.datasource.username = root
spring.datasource.password = root

# Hibernate
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.dialect = org.bsoftware.beagle.server.dialects.MySQL8MyISAMDialect

# Multipart
spring.servlet.multipart.max-file-size = 1024MB
spring.servlet.multipart.max-request-size = 1024MB